### ISSUE TITLE
It's not using my pre-existing Traefik config

### ISSUE THREAD

**Issue by charl3y15** [Rahn-IT/traefik-gui#1]
Is it supposed to? I pointed to the right path but all I see is 
![image](https://github.com/user-attachments/assets/edb41832-b4df-4fda-b55f-d046a087f44b)

**Comment by charl3y15** [comment]
I have this mapping /mnt/user/appdata/traefik:/app/traefik

**Comment by acul009** [comment]
The routes are saved in an sqlite database and only exported to the traefik format.

If you‘re configs are simple enough I might be able to add an import. Do you have an example you could share?

There‘s also a few more things:
- thanks for the screenshot, I just spotted a bug in my export code.
- Https routes are not yet implemented
- The host field doesn‘t require a protocol. `panel.example.com` should be enough.

I‘m a bit busy at the moment, but I‘ll fix the bug and add Https if I find some time :)

**Comment by charl3y15** [comment]
No rush! I just noticed when I added it it didn't seem to point to the right location. Is Traefik still able to read when I add entries? for example, the panel.cd1git.com

Most of my config that I would like to be imported look like

```
    dockerwebgui:
        entryPoints:
          - https
        rule: 'Host(`dockerwebgui.domain.com`)'
        service: dockerwebgui
        middlewares:
          # - "crowdsec-bouncer@file"
          - "securityHeaders"
          - "authentik@file"
```

I am not sure if the comments would make it more difficult to import
